### ISSUE TITLE
Document Orderbook specs  and todo's

### ISSUE THREAD

**Issue by robvanmieghem** [rivine/recordchain#12]
Currently it is unknown what needs to be done for the orderbook. Re-watch the recorded sessions with Kristof and write the specs in Orderbook/specs.
Also create issues for the todo's

**Comment by andrewayoub** [comment]
after contacting Jimber people here are the specs: 
The orderbook is a tool to automate the atomic swap. When 2 orders match each other, the swap will be executed automatically. 
## Fields
DateTimeAdded | IP | AmountFrom | AmountTo | From | To
-- | -- | -- | -- | -- | --
04/06/2018 11:33:22 | 18.223.45.5 | 1 | 2000 | BTC | TFT

DateTimeAdded : the time the order was added into the orderbook
IP: ip address of the node
AmountFrom: amount of coins you want to “sell”
AmountTo: amount of coins you want to get for it
From: Coin you want to “sell”
To: Coin you want to receive
## API’s
Create order
Read orders ( with some filters) 
Delete order

Orders will not be updated. For example with a partial swap, the order will be removed and a new one will be created.
## Keep alive
each node will send messages ( http calls with jwt and ip of node ) to the orderbook. 
When the orderbook doesn’t receive these messages from the node, the orders will be deleted. 
A node will always send his orders when a connection with the orderbook is created.

**Comment by Hamdy** [comment]
https://github.com/rivine/recordchain/blob/master/JumpScale9RecordChain/apps/orderbook/specs.md

**Comment by ahussein** [comment]
@Hamdy The above link is broken. it gives 404

**Comment by andrewayoub** [comment]
@ahussein link fixed
