### ISSUE TITLE
Expand Jumpscale currency framework  to include more digital coins

### ISSUE THREAD

**Issue by Hamdy** [rivine/recordchain#13]
Currently we have a numeric data type in Jumpscale that can understand currency

```
In [11]: x =j.data.types.numeric.fromString('10 USD')

In [12]: j.data.types.numeric.bytes2cur(x)
Out[12]: 10.0
```

We want to expand it to understand / convert and fetch  latest values for (BTC, ETH, XRP, TFT)

**Comment by andrewayoub** [comment]
BTC was already supported added ETH and XRP but TFT needs a way to determine it's price

**Comment by Hamdy** [comment]
TFT needs to be added

**Percentage**
90%
