### ISSUE TITLE
implement test in zdb client

### ISSUE THREAD

**Issue by despiegk** [rivine/recordchain#50]
/code/github/rivine/recordchain/JumpScale9RecordChain/clients/zdb/ZDBClient.py

because new implementation now of index (in zdb directly)

**Comment by despiegk** [comment]
use js9 'j.clients.zdb.test(start=True)'

**Comment by zaibon** [comment]
does the new index is already supported by zdb? or this is a coming feature ?
Should I wait the client to be updated before using it in my projects ?
