### ISSUE TITLE
gedis needs ssl

### ISSUE THREAD

**Issue by despiegk** [rivine/recordchain#7]
implement client/server over ssl in gedis
test with redis over ssl (as client)

**Comment by ashraffouda** [comment]
ssl support added to gedis, and to jumpscale redis client  as well

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/37946069-b2814196-3183-11e8-9e44-952b355ab29e.png)

just doing like this break everything,

would have been better to think about
- how when not using key (needs to be option)
- how to generate the key
- some more doc

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/37947230-3793c7cc-318a-11e8-82d8-55dc9317b3ea.png)
i just compiled to newest ssh2 client locally, see these issues
PLEASE get paramiko back as std lib and when used in zrobot we can use other, do this asap please

**Comment by despiegk** [comment]
use/fix https://github.com/Jumpscale/lib9/issues/208
so it becomes easy to use this server

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/37947607-78a080e6-318c-11e8-8e85-1db6f6ba3b29.png)
now optional

**Comment by despiegk** [comment]
redis config client has been extended to have support for the keyfile but needs to be optional

![image](https://user-images.githubusercontent.com/6021844/37951088-770f4186-319b-11e8-9c8f-5c6308871bf3.png)

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/37951256-19f8fea0-319c-11e8-9d68-57f76f57d043.png)
use this redis client implementation

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/37951265-20c534d8-319c-11e8-9209-8c7feebb4e00.png)

use this client implementation for redis

**Comment by despiegk** [comment]
implement aub:
![image](https://user-images.githubusercontent.com/6021844/37951490-d98078e8-319c-11e8-8dec-3036596a8743.png)

**Comment by ashraffouda** [comment]
now the certficate generation is part of the code, ssl(sal) is fixed as well as some fixes here and there in redisconfig and gedis 
the test still needs to be done
